{{- if .Values.onepassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: k8s-sentinel-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-sentinel.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.onepassword.itemPath | quote }}
{{- end }}
